### ISSUE TITLE
Can't open Configure Controls menu

### ISSUE THREAD

**Issue by amcvfx** [itamarcu/AlternativeRotation#13]
With Alternative Rotation active the Configure Controls menu no longer opens.

![image](https://user-images.githubusercontent.com/35099081/148648919-c8234538-d1cd-4946-98a3-85ae80426720.png)

On Foundry 9.242

**Comment by Sasmira** [comment]
Hello Hello, 
same problem here too with last version of Alternative Rotation and fvtt 9.242.
<img src="https://cdn.discordapp.com/attachments/715986155975344211/929432596016926720/unknown.png">

**Comment by itamarcu** [comment]
Fixed in v2.0.1.  (I had a code typo for the default modifier hotkeys)

If you still see errors, you should be able to reset your keybindings to fix it for good.  If it doesn't work or if you don't want to reset your keybindings, you can DM me on discord (shem#0226).
