### ISSUE TITLE
Shift + R doesn't seem to work (or even exist)

### ISSUE THREAD

**Issue by dmrickey** [itamarcu/AlternativeRotation#15]
Holding R to change the rotation works just fine, however, when I also hold shift, it behaves the same as just holding R. It's still incremental rotations and not a larger snap distance. The readme says that "shift + R" is configurable, but I don't even see a place to configure it in the mod's settings.
![image](https://user-images.githubusercontent.com/3664822/149985773-f77883e5-ca7b-4fb1-b2eb-d2c058faed38.png)

Foundry v9 242
Alt Rotation v2.1.1
system pf1 0.80.7
Only Alt Rotation and lib wrapper are enabled.

**Comment by itamarcu** [comment]
@dmrickey it's configurable in Configure Controls -> Alternative Rotation.  By default it should say "ShiftLeft, ShiftRight" there.

**Comment by dmrickey** [comment]
Gotcha. I didn't realize that menu had any mod options in it. It would be nice to include that in the readme (I saw that the readme said "configurable" but it never occurred to me to look in that menu since it's new and I'd never used it before)

**Comment by itamarcu** [comment]
Updated readme to be clearer now!
