### ISSUE TITLE
Rotation on tiles

### ISSUE THREAD

**Issue by dmrickey** [itamarcu/AlternativeRotation#16]
If I'm rotating a token, the token live updates with the rotation to show me the update. 

If I rotate a tile, I only see the final update when I release the rotation button. Similarly, if I try to resize a rotated tile, then it snaps back to the default rotation during resize, then goes back to the rotation when the size is picked. This makes it a bit harder to resize non-square tiles because it immediately jumps to a different size because of how it's oriented when it goes back to the default rotation

**Comment by itamarcu** [comment]
Fixed in v2.1.2.
