### ISSUE TITLE
[Bug] Can’t select multiple tokens with rectangle selection

### ISSUE THREAD

**Issue by mrkwnzl** [itamarcu/AlternativeRotation#2]
With Alternative Rotation active, I cannot select multiple tokens using the rectangle selection. I can, however, select multiple tokens when I shortly hover over the token while rectangle selecting.

Video of what happens:

[Selection.mp4 2.zip](https://github.com/itamarcu/AlternativeRotation/files/5249440/Selection.mp4.2.zip)

**Comment by itamarcu** [comment]
Fixed in 0.3.2.

I'm pretty sure it was just a visual bug - the `refresh()` function for each token wasn't called, so it didn't show the selection thing, until the first time you tried to rotate a token.

Let me know if it remains in any way!
