### ISSUE TITLE
Interferes with core <<shift>> to ignore grid snapping for tokens

### ISSUE THREAD

**Issue by ref2335** [itamarcu/AlternativeRotation#9]
Love the module, however the use of shift seems to interfere with the core use of shift when placing a tile when attempting to place and ignore grid snapping.  Is this something I am doing wrong or is this a known issue?

**Comment by itamarcu** [comment]
I think this was reported in #5 too.  I'll take another look.

**Comment by itamarcu** [comment]
@ref2335 are you sure this is a bug?  This module overrides the behavior of holding shift and then starting to drag a token/tile, but it still allows you to start dragging a token/tile and then hold shift while you release it (to ignore snapping).  Does that work for you?
